### PR TITLE
A few improvements.

### PR DESCRIPTION
**Pull request by tatsumoto-ren**
I made a few changes. Hope you'll like them.
* ability to read `subsync_path` from a separate config file so that the user doesn't need to change the source code.
* path to the subtitle file is detected automatically. I usually have my subs in a separate folder and moving them back in forth for re-timing is not very convenient. 
* refactored code a bit, made everything `local`.
* Added a bunch of line breaks to README because lines were too long to be readable from a text editor.

### CODE REVIEW

**Comment by joaquintorres** [comment]
It looks absolutely amazing, thank you so much! 
However, I'm getting the following error every time I try to run it:

`[autosubsync] Lua error: /home/joaquin/.config/mpv/scripts/autosubsync.lua:101: attempt to index local 'ret' (a nil value)`
which, if I'm not mistaken, involves lines

`    if ret.error == nil then` 
and 
`    local ret = subprocess { config.subsync_path, video_path, "-i", subtitle_path, "-o", retimed_subtitle_path }`

I don't really know Lua, but it looks like some issue with scoping and local variables. Do you know what it could be? It seems to be a quick fix, but I don't know much about how Lua variables work.
(Needless to say, I'll merge the request as soon as it's functioning properly)

**Comment by tatsumoto-ren** [comment]
Strange. mp.command_native always returns a table so from my point of view it's impossible to receive a `nil` response.
I'll try to look into it.

**Comment by tatsumoto-ren** [comment]
Added a `nil` check to avoid the crash. But I still don't know how you got that error.

**Comment by joaquintorres** [comment]
Well, i tried a lot of things, since at first I just kept getting the `nil` error again and again. I thought it might be that the paths weren't being processed correctly by ffsubsync, but later it seemed as if the problem had to do exclusively with line 
```lua
local ret = subprocess { config.subsync_path, video_path, "-i", subtitle_path, "-o", retimed_subtitle_path }
```
Since my version was still working, I tried to see if changing things to make it more like the original code would work, so I replaced the above line with 

```lua
t = {}
t.args = { config.subsync_path, video_path, "-i", subtitle_path, "-o", retimed_subtitle_path }
local ret = utils.subprocess(t)
```
I don't know why but this worked. It's really strange, since I tried `local ret = utils.subprocess { config.subsync_path, video_path, "-i", subtitle_path, "-o", retimed_subtitle_path }` and it also returned `nil`.
Tomorrow I'll do more tests and look up why this works, if nothing goes suddenly wrong I'll do the merge. Still, it's puzzling that it worked for you but not for me. I'm guessing it may have to do with `subprocess` 's argument being a non-`local` variable, but I have to read more to know for sure.

**Comment by joaquintorres** [comment]
By the way, I'm using an older version of `mpv` (0.27.2-1ubuntu1) and `ffsubsync` (0.3.7), so maybe that's the reason for the different behaviors. I'll update ffsubsync, but the mpv version is the latest for Ubuntu 18.04, so you'll probably still have a newer one if you're using an Arch-based distro, installing from source, etc. 
   If it happens to be a problem with `mpv`'s version, I would still rather have compatiblity with Ubuntu LTS repos than forcing users to upgrade.

**Comment by tatsumoto-ren** [comment]
>I'm using an older version of mpv (0.27.2-1ubuntu1)

Oh, thank you for telling this. This makes all the difference. The reason why I changed `utils.subprocess` to a wrapper around `mp.command_native` is because in mpv `0.32.0` `utils.subprocess` is considered deprecated. 

In this particular example local vs global doesn't make any difference, though using globals in general may cause unexpected behavior.

**Comment by joaquintorres** [comment]
Great! I'll take it into account and take a better look at the documentation. I'm doing the merge now and making a new branch for v0.32, hopefully we can remove the deprecated stuff as soon as Ubuntu 18.04 repos are updated or people migrate to 20.04.
Thank you again! Code looks fantastic now.

**Comment by tatsumoto-ren** [comment]
Thank you!

**Pull request merged**
